version: 2.1
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
  coveralls: coveralls/coveralls@1.0.6

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: develop
jobs:
  build:
    docker:
      - image: circleci/node:14.17
        environment: 
          PGHOST: 127.0.0.1
          PGUSER: postgres
          NODE_ENV: test
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: politico_test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          name: install-npm-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - ./node_modules
      - run: #run tests
          name: test
          command: npm run test
      - run: # run code coverage report
          name: code-coverage
          command: npm run coveralls
      - run: # run build
          name: Build
          command: npm run build
      # - coveralls/upload


