version: 2.1
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
  coveralls: coveralls/coveralls@1.0.6

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: develop
jobs:
  build:
    docker:
      - image: circleci/node:14.17
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          # TEST_DATABASE_URL: postgresql://root@localhost/politico_test
          POSTGRES_USER: root
          POSTGRES_DB: politico_test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          name: install-npm-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: update postgres client
          command: sudo apt-get update
      - run:
          name: wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: echo '/usr/lib/postgresql/9.6/bin/:$PATH' >> $BASH_ENV
      - run: # database setup
          name: create database
          command: |
             sudo psql --host localhost -U postgres -p 5432 -c "create database politico_test;"
      - run: #run tests
          name: test
          command: npm run test
      - run: # run code coverage report
          name: code-coverage
          command: npm run coveralls
      - run: # run build
          name: Build
          command: npm run build
